<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
        <relativePath/>
    </parent>

    <groupId>dev.dasmido</groupId>
    <artifactId>nexus-pass-vault</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Nexus Pass Vault</name>

    <modules>
        <module>nexus-jpa</module>
        <module>nexus-rest</module>
        <module>nexus-svelte</module>
        <module>nexus-app</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <svelte.build>false</svelte.build>
    </properties>

    <profiles>
        <profile>
            <id>with-svelte</id>
            <properties>
                <svelte.build>true</svelte.build>
            </properties>
        </profile>
    </profiles>

</project>

