apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-pass-vault
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-pass-vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nexus-pass-vault
    spec:
      containers:
        - name: npv
          image: dasmod/nexus-pass-vault:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: nexus-pass-vault-config
            - secretRef:
                name: nexus-pass-vault-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"