apiVersion: v1
kind: Secret
metadata:
  name: nexus-pass-vault-secrets
  namespace: default
type: Opaque
stringData:
  NEXUS_DB_URL: "jdbc:postgresql://nexus-pass-vault-db:5432/nexus_pass_vault"
  NEXUS_DB_USERNAME: "nexus_pass_vault_user"
  NEXUS_DB_PASSWORD: "nexus_pass_vault_password"